### ISSUE TITLE
Questions about the robustness of the current popular monocular 3D object detector

### ISSUE THREAD

**Issue by dragonfly606** [xinzhuma/3dodi-survey#2]
In my experiments, I noticed that the current popular algorithms are not robust enough, that is, under the same configuration (even with a fixed random number seed), the accuracy of the evaluation results will have a difference of about 2% (which is quite large in the field of monocular 3D object detection), how to deal with this phenomenon in the experiment? Do I need to do a few more experiments each time to verify the validity of the idea or adjust the hyperparameters and then take the average to verify? This again has to take a lot of extra time and resources, looking forward to your reply

**Comment by xinzhuma** [comment]
You are right. At present, the algorithm on the KITTI list is not stable, and this is mainly caused by the KITTI data set. For stable experimental results, it is recommended to take the average value of multiple tests, such as table 4 in https://arxiv.org/pdf/2208.07137.pdf  or table 20 in https://arxiv.org/pdf/2207.10758.pdf




在 2023年3月12日，上午11:31，longfeiyan ***@***.******@***.***>> 写道：



In my experiments, I noticed that the current popular algorithms are not robust enough, that is, under the same configuration (even with a fixed random number seed), the accuracy of the evaluation results will have a difference of about 2% (which is quite large in the field of monocular 3D object detection), how to deal with this phenomenon in the experiment? Do I need to do a few more experiments each time to verify the validity of the idea or adjust the hyperparameters and then take the average to verify? This again has to take a lot of extra time and resources, looking forward to your reply

**Comment by dragonfly606** [comment]
Thanks a lot!
